spring:
  application:
    name: spring_kafka

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # we can provide multiple servers not only one
      group-id: myGroup # group of consumers