spring:
  application:
    name: spring_kafka

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # we can provide multiple servers not only one
      group-id: myGroup # group of consumers
      auto-offset-reset: earliest # what we want to do in case we lose the reset or we want to reset out offset. (Automatically reset the offset to the earliest offset)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # using th key deserializer cos the produces give us a message serialized.
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # using th value deserializer cos the produces give us a message serialized.

    producer:
      bootstrap-servers: localhost:9092 # same broker
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # using the key deserializer cos we are the produces and will send a message serialized.
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # using the value deserializer cos we are the produces and will send a message serialized